/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code401challenges;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test public void testInsertShiftArrayMethod() {
        int[] testDataOne = new int[] {2,4,6,8};
        int[] testDataTwo = new int[] {4,8,15,23,42};

        assertEquals("[2, 4, 5, 6, 8]", code401challenges.ArrayShift.insertShiftArray(testDataOne, 5));
        assertEquals("[4, 8, 15, 16, 23, 42]", code401challenges.ArrayShift.insertShiftArray(testDataTwo, 16));
    }
}


